// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  DB: D1Database;
  STORAGE: R2Bucket;
  VIDEO_WORKFLOW: Workflow;
  DE_API_URL: string;
  ASSET: Fetcher;
}
